### ISSUE TITLE
Is there any way to customize or disable `selectionColor` when a cell is selected?

### ISSUE THREAD

**Issue by fullc0de** [WenchaoD/FSPagerView#121] opened 2018-03-09 05:50 UTC
Hello WenchaoD.

Like a title, I am looking for a way to customize or disable `selectionColor` on `FSPagerViewCell`. Actually, I don't want a visual effect for highlighting like changing backgroundColor. Until now, I could find any way to achieve that.  

Is there any interface or method to do that? Or should I fork this repo and modify a source code?

**Comment by omidshz100** [comment] 2018-06-11 04:35
hello you can fix it by this function of delegate : 
 func pagerView(_ pagerView: FSPagerView, shouldHighlightItemAt index: Int) -> Bool{
        return false
    }
but the problem is clickable is not work

**Comment by wsof401** [comment] 2018-07-03 09:30
that is a fucking implementation, the only way is to move the selection logic to shouldHighlightItemAt or shouldSelectItemAt.

**Comment by decazuk** [comment] 2018-12-18 08:37
You can inherit `FSPagerViewCell` and override `isHighlighted` and `isSelected`

**Comment by klauslanza** [comment] 2019-03-12 15:08
A possible solution to prevent the highlighting (while waiting for an approved PR) is https://github.com/WenchaoD/FSPagerView/issues/186 .

**Comment by klauslanza** [comment] 2019-04-08 16:09
You're right @wsof401, this is not an optimal solution, sorry. Still waiting for somebody to merge the proposed solution..

**Comment by Wbqqqq** [comment] 2019-05-19 08:50
why set shouldHighlightItemAt false , clickable is not work? I'm not understand.

**Comment by klauslanza** [comment] 2019-05-20 07:35
You are right, this was a workaround only in my use case. Hope the PR gets merged soon.

**Comment by wmadao11** [comment] 2020-01-07 07:13
Moving clicked logic to `shouldSelectItemAt` is a workaround for me.
```
    func pagerView(_ pagerView: FSPagerView, shouldSelectItemAt index: Int) -> Bool {
        // do clicked stuff
        // false to disable selection style
        return false
    }
    //func pagerView(_ pagerView: FSPagerView, didSelectItemAt index: Int) -> Bool {
    //    // do clicked stuff
    //}
```

**Comment by nilhy** [comment] 2020-01-08 09:14
这个设计太不合理了, 强制继承太局限了,有时候cell 根本比你的案例中更为复杂,即时必须继承, 那请selectionColor 公开不就好了. 好多需求根本不需要那个阴影和背景色效果

**Comment by wsof401** [comment] 2020-01-08 10:40
Please close this issue.
Author  seems has given this repo up.
Or may someone willing to override it, contact me plz

**Comment by fullc0de** [comment] 2020-01-10 03:15
Hi guys, I haven't caught up with this issue for a long time. :-)

I thought `FSPagerViewCell` was not the prototype cell but the one which offers primary UI functionality. In that perspective, `selectionColor` is the one of functionality I expected. If the author of the control didn't mean that and it is meant be overridden depending on each user's needs, I think `selectedForegroundView` may have to be `public` property. 

I carefully expect that a lots of users would like to use `FSPagerViewCell` as it is without creating their own cell to meet their own requirements. 

Anyways, I will close this issue after a few days because of listening opinions from others about my point. 

Thanks.

**Comment by fullc0de** [comment] 2020-01-15 04:30
closed the issue.

**Closed** 2020-01-15 04:29 UTC
